- .travis.yml
- README.md
- ext/plugins/index.js
- ext/plugins/lint-bare-strings.js
- index.js
- node-tests/helpers/template-compiler.js
- node-tests/nodetest-runner.js
- node-tests/unit/linting-compiler-test.js
- package.json
> WIP: Refactor into a linter

- README.md
- ext/helpers/calculate-location-display.js
- ext/plugins/lint-bare-strings.js
- ext/plugins/lint-block-indentation.js
- ext/plugins/lint-triple-curlies.js
- node-tests/unit/plugins/lint-block-indentation-test.js
When an HTML element node is multi-line, the `block-indentation` rule now requires that it start and end at the same indentation level.
Example:
```
<div>
<p>Stuff goes here</p></div>
```
Would result in the following message:
```
Incorrect indentation for `div` beginning at ('layout.hbs'@ L1:C0).
Expected `</div>` ending at ('layout.hbs'@ L2:C30)to be at an indentation
of 0 but was found at 24.
```
Fixes #30.
> Implement HTML element block indentation requirment.

- ext/plugins/lint-block-indentation.js
- node-tests/helpers/rule-test-harness.js
- node-tests/unit/plugins/lint-block-indentation-test.js
Fixes #36.
Now works properly:
```hbs
{{#if isMorning}}
Good morning
{{else if isAfternoon}}
Good afternoon
{{else}}
Good night
{{/if}}
```
> Detect and handle blocks nested inside inverse.

- broccoli-template-linter.js
- package.json
* Move logging into `postProcess`
* Return an object with `messages` and `output` from `processString`
---
Before:
```
% ember b && ember b
version: 2.4.2
Building..Non-translated string used ('sample-2-4-0/templates/application.hbs') `Welcome to Ember`
Built project successfully. Stored in "dist/".
version: 2.4.2
Built project successfully. Stored in "dist/".
```
After:
```
% ember b && ember b
version: 2.4.2
Building..Non-translated string used ('sample-2-4-0/templates/application.hbs') `Welcome to Ember`
Built project successfully. Stored in "dist/".
version: 2.4.2
Building..Non-translated string used ('sample-2-4-0/templates/application.hbs') `Welcome to Ember`
Built project successfully. Stored in "dist/".
```
Fixes https://github.com/rwjblue/ember-cli-template-lint/issues/34.
> Enable log messages on initial build when cached.

- broccoli-template-linter.js
- node-tests/acceptance/broccoli-test.js
Queues up all messages until after the build has finished, summarizes number of errors.
More like broccoli-jshint.
> Make console output a bit better.

- README.md
- blueprints/ember-cli-template-lint/files/.template-lintrc.js
- lib/get-config.js
- node-tests/unit/plugins/lint-bare-strings-test.js
See #58. The default configuration was changed to allow the following characters as bare strings: `(),.&+-=*/#%!?:[]{}`
> Add default whitelist for bare-strings

- CHANGELOG.md
- README.md
- lib/get-config.js
Closes https://github.com/rwjblue/ember-cli-template-lint/issues/31.
> Do not enable rules by default.

- README.md
- blueprints/ember-cli-template-lint/files/.template-lintrc.js
- ext/plugins/index.js
- ext/plugins/lint-html-comments.js
- node-tests/unit/plugins/lint-html-comments-test.js
Forbid HTML comments in favor of Handlebars comments (fixes #64)
> Implement html-comments rule

- ext/plugins/lint-block-indentation.js
- node-tests/unit/plugins/lint-block-indentation-test.js
If the block children are inline elements, then there can be important reasons for them to appear on the same line. For example:
```javascript
<div>
<span class="key">key</span>:<span class="value">value</span>
</div>
```
will render as
```
key: value
```
but
```javascript
<div>
<span class="key">key</span>:
<span class="value">value</span>
</div>
```
will render as
```
key:
value
```
The block indentation rule was previously forbidding the first version because the second ```<span>```'s column number is not two. This commit makes the indentation rule aware of previous content on the same line, whether it is an element/mustache node or text.
> Make the block-indentation rule aware of leading content

- ext/helpers/ast-node-info.js
- ext/plugins/base.js
- ext/plugins/index.js
- ext/plugins/internal/lint-configuration-html-comments.js
- ext/plugins/internal/remove-configuration-html-comments.js
- ext/plugins/lint-html-comments.js
- node-tests/helpers/rule-test-harness.js
- node-tests/unit/plugins/internal/remove-configuration-html-comments-test.js
- node-tests/unit/plugins/lint-bare-strings-test.js
- node-tests/unit/plugins/lint-block-indentation-test.js
- node-tests/unit/plugins/lint-html-comments-test.js
- node-tests/unit/plugins/lint-triple-curlies-test.js
Fixes https://github.com/rwjblue/ember-cli-template-lint/issues/67
We're no longer removing linting configuration html comments in individual plugins, this now happens as a final step in an `internal-remove-configuration-html-comments` plugin
/cc @rwjblue
> Support per-template configuration comments

- README.md
- blueprints/ember-cli-template-lint/files/.template-lintrc.js
- ext/plugins/index.js
- ext/plugins/lint-nested-interactive.js
- node-tests/unit/plugins/lint-nested-interactive-test.js
Disallow nested interactive elements (`<button>` and `<a>`).
Because of `HTML5` standard technically they cannot be rendered nested, they became sibling. In HTMLBars it possible and I guess it's related to the fact it's JavaScript rendering based. Anyway due of babbling, I don't think you benefit much of that.
[mode info](https://html.spec.whatwg.org/multipage/semantics.html#the-a-element)
**EDIT:** I've copy the todos
> neseted interactive rule

- README.md
- blueprints/ember-cli-template-lint/files/.template-lintrc.js
- ext/helpers/ast-node-info.js
- ext/plugins/lint-bare-strings.js
- node-tests/helpers/rule-test-harness.js
- node-tests/unit/plugins/lint-bare-strings-test.js
These changes update the `bare-strings` rule to allow the following configuration:
* boolean -- `true` for enabled / `false` for disabled
* array -- an array of whitelisted strings
* object -- An object with the following keys:
* `whitelist` -- An array of whitelisted strings
* `globalAttributes` -- An array of attributes to check on every element.
* `elementAttributes` -- An object whose keys are tag names and value is an array of attributes to check for that tag name.
We have also update the default blueprinted value to be `true`, which defaults the configuration to:
```js
{
whitelist: ['(', ')', ',', '.', '&', '+', '-', '=', '*', '/', '#', '%', '!', '?', ':', '[', ']', '{', '}'],
globalAttributes: GLOBAL_ATTRIBUTES,
elementAttributes: TAG_ATTRIBUTES
};
```
> Implement attribute checking for `bare-strings` rule.

- README.md
- blueprints/ember-cli-template-lint/files/.template-lintrc.js
- ext/helpers/ast-node-info.js
- ext/plugins/deprecations/lint-deprecated-each-syntax.js
- ext/plugins/index.js
- node-tests/unit/plugins/deprecations/lint-deprecated-each-syntax-test.js
This covers deprecations for the `in` syntax of `{{#each}}`, such as
`{{#each post in posts}}`.
> [feature deprecated-each-syntax] Linting for each

- broccoli-template-linter.js
* Ensure that multiple errors are listed on separate lines.
* Fix formatting when `error.line` / `error.column` are missing.
* Fix formatting when `error.source` is missing.
Fixes #95.
> Fix issues with error message display.

- lib/commands/print-failing.js
- package.json
Now emits the following output:
```
Add the following to your `.tempate-lintrc.js` file to mark these files as pending.
pending: [
{
"moduleId": "sample-2-4-0/templates/application",
"only": [
"bare-strings"
]
}
]
```
> Update print-failing command to emit rule specific stuff.

- broccoli-template-linter.js
Seeing error messages like:
```
invalid-interactive: Interaction added to non-interactive element(dummy/templates/application @ L166:C35):
`<li><button class="button" {{action "reload"}}>Hard Reload</button></li>`
```
> Add space to error message

- package.json
> remove ember-try dependency

- index.js
fixes https://github.com/rwjblue/ember-cli-template-lint/issues/147
**before:**
**after:**
> added `baseDir` for caching purposes

- index.js
Currently console output is using the native console instead of ember-cli's `ui` object, breaking CI runs when using the `--silent` flag and piping test output to an XUnit file. This is happening probably accidentally as the necessary code is there. It's just `index.js` setting the option as `_console` while `broccoli-template-linter.js` expects it as `console`.
> Fix console using ui.writeLine

- broccoli-template-linter.js
- node-tests/acceptance/broccoli-test.js
Prior to this change the test files emitted from ember-cli-template-lint would not be disabled by the "no lint" checkbox in ember-cli's default test harness.
---
Without "Disable Linting" checked:
With "Disable Linting" checked:
> Update to use common extension for template linting.

- node-tests/blueprints/ember-cli-template-lint-test.js
- package.json
Here is the fix for the failing greenkeeper update #221
> Update ember-cli-blueprint-test-helpers and fix tests

- broccoli-template-linter.js
- index.js
- node-tests/acceptance/broccoli-test.js
- package.json
similar to https://github.com/ember-cli/ember-cli-eslint/pull/176
/cc @rwjblue
> Add test module grouping by default

- index.js
When I `yarn link`ed the addon to develop, the addon detected my app's tests as being qunit instead of mocha, and so the addon didn't generate any tests
> fix addon not working when `yarn link`ed

- broccoli-template-linter.js
@rwjblue 
This fix should prevent adding empty or null errors to errors array.
Before:
```js
['','','','','error',] // self._errors
```
After
```js
['error'] // self._errors
```
It will fix an issue with inproper fomratting and counting. #273
> Prevent empty errors

- index.js
- package.json
- yarn.lock
`semver`'s `satisfies` has somewhat bizarre issues around matching prerelease versions. In this case, we don't _really_ care what version you are using at all, we just want to check if you have a given dependency installed.
This updates to using a new API in ember-cli-version-checker to simply check if a given dep exists or not.
Fixes https://github.com/rwjblue/ember-cli-template-lint/issues/286
> Use dep.exists() to check for presence.

- index.js
This PR is a backport of #344 to the `v0.7.x` branch
> Backport: Allow ember-qunit and ember-mocha directly

- lib/plugins/remove-configuration-html-comments.js
Fixes #444.
ember-cli-htmlbars-inline-precompile becomes parallelizable if all the AST transforms inside it are parallelizable. The protocol it supports is *nearly* the same as the one used by broccoli-babel-transpiler itself, but not quite.
In particular, the special key is named `parallelBabel` instead of `_parallelBabel`, the `buildUsing` property is mandatory, and there is no recursion to look for deeper unserializable things.
> Support usage inside parallel babel inside inline-hbs

- .travis.yml
- package.json
Is it still recomended to use ember-cli-template-lint @rwjblue ? It is still shipped with ember-cli's default blueprints. So I would assume a yes. Plus, I haven't found any RFC to deprecate usage of ember-cli-eslint and ember-cli-template-lint. But would this change require an RFC at all?
In the meantime, let's drop Node 6 / 8 / 11, it will allow dependabot to merge a few PRs. And ember-cli-template-lint is still in a beta cycle, so no major bump would be required?
> Drop NodeJs 6, 8, 11

- blueprints/ember-cli-template-lint/recommended-files/.template-lintrc.js
- blueprints/ember-cli-template-lint/recommended-with-bare-strings-files/.template-lintrc.js
- node-tests/blueprints/ember-cli-template-lint-test.js
This set is already used in ember-cli blueprints.
EDIT: I have removed the `breaking` label, as it is a change affecting only the blueprints 😄
> Update blueprint to use `octane` config

- ember-cli-build.js
- index.js
Fixes #512 
I discovered this while investigating why parallel babel builds were not working in my app. While I don't use ember-cli-template-lint personally, it's in the ember-cli blueprint so all brand new ember apps are prevented from running in parallel. I already did similar over at https://github.com/pzuraq/ember-simple-set-helper/pull/3
> Allow ast-plugin to run in parallel
