.travis.yml, README.md, ext/helpers/calculate-location-display.js, ext/plugins/index.js, ext/plugins/lint-bare-strings.js, ext/plugins/lint-block-indentation.js, index.js, node-tests/fixtures/config/disable-all.js, node-tests/helpers/template-compiler.js, node-tests/nodetest-runner.js, node-tests/unit/linting-compiler-test.js, node-tests/unit/plugins/lint-block-indentation-test.js, package.json
refs zestyzesty/hack-day#8
* Add block indentation linting
* Log linted items to console
* Add linting for bare strings
=> Zesty Hackday Work:

ext/plugins/index.js, ext/plugins/lint-triple-curlies.js, node-tests/unit/plugins/lint-triple-curlies-test.js
Closes #8.
/cc @halfdan for review
=> Add triple curly bracket rule.

ext/plugins/lint-bare-strings.js
=> Add quoted string expression example

ext/plugins/base.js, ext/plugins/lint-bare-strings.js, ext/plugins/lint-block-indentation.js, ext/plugins/lint-triple-curlies.js
This builds on top of #11 (to avoid requiring a rebase/rewrite of it).
=> Refactor plugins to reduce duplication.

.eslintrc.js, ext/.eslintrc.js, ext/helpers/calculate-location-display.js, ext/plugins/base.js, ext/plugins/index.js, ext/plugins/lint-bare-strings.js, ext/plugins/lint-block-indentation.js, ext/plugins/lint-triple-curlies.js, node-tests/.eslintrc.js, node-tests/fixtures/config/disable-all.js, node-tests/helpers/template-compiler.js, node-tests/nodetest-runner.js, node-tests/unit/eslint-test.js, node-tests/unit/linting-compiler-test.js, node-tests/unit/plugins/lint-block-indentation-test.js, node-tests/unit/plugins/lint-triple-curlies-test.js, package.json
Copied most of the config from ember-cli.
=> Enable linting via ESLint.

README.md, ext/plugins/base.js, node-tests/unit/plugins/lint-block-indentation-test.js, node-tests/unit/plugins/lint-triple-curlies-test.js
Syntax is:
```hbs
{{! do bad things ;P }}
```
```hbs
{{{foo}}}
```
Closes #17.
=> Add ability to disable all rules or a subset of rules.

README.md
=> Refactor README.

README.md
Adds `npm run test-node` to the "Running Tests" section of "Contributing"
=> Document command for running node tests

node-tests/unit/plugins/lint-block-indentation-test.js, package.json
Fixed by:
https://github.com/tildeio/htmlbars/pull/450
https://github.com/tildeio/htmlbars/pull/451
https://github.com/tildeio/glimmer/pull/91
https://github.com/tildeio/glimmer/pull/93
Closes #36
=> Failing test for #36.

ext/plugins/lint-block-indentation.js, node-tests/unit/plugins/lint-block-indentation-test.js
=> Remove requirement that all block statements are multiline.

ext/plugins/lint-block-indentation.js, node-tests/unit/plugins/lint-block-indentation-test.js
=> Prevent triggering errors on void tags.

.eslintrc.js, README.md, broccoli-template-linter.js, ext/.eslintrc.js, ext/plugins/base.js, ext/plugins/lint-block-indentation.js, lib/.estlintrc.js, lib/get-config.js, node-tests/.eslintrc.js, node-tests/helpers/rule-test-harness.js, node-tests/unit/plugins/lint-block-indentation-test.js
=> Require nested children to be properly indented.

ext/plugins/lint-block-indentation.js, node-tests/unit/plugins/lint-block-indentation-test.js
=> Fix messages for invalid indented children.

README.md, ext/plugins/lint-bare-strings.js, node-tests/unit/plugins/lint-bare-strings-test.js
=> Add whitelist to bare-strings.

.template-lintrc.js, index.js, tests/acceptance/index-test.js, tests/dummy/app/templates/application.hbs
This takes all the hard work from @GavinJoyce in #72 and adds an additional commit to make those tests pass properly.
Closes #72.
=> Add acceptance test.

ext/plugins/lint-block-indentation.js, node-tests/unit/plugins/lint-bare-strings-test.js, node-tests/unit/plugins/lint-block-indentation-test.js, node-tests/unit/plugins/lint-html-comments-test.js, package.json
=> Fix issues from adding text/comment node location in HTMLBars.

README.md, blueprints/ember-cli-template-lint/files/.template-lintrc.js, ext/plugins/index.js, ext/plugins/lint-self-closing-void-elements.js, node-tests/unit/plugins/lint-self-closing-void-elements-test.js
related #77
tell me if there is anything to fix
=> Added lint-self-closing-void-elements rule

index.js, package.json
=> Set minimum ember-cli version.

broccoli-template-linter.js
Fixes https://github.com/rwjblue/ember-template-lint/issues/33
=> Include rule name in all error messages.

README.md
https://github.com/rwjblue/ember-cli-template-lint/issues/118 wouldn't be an issue if `hinting` option was described. Let's make it easier for future developers.
=> Add description of `hinting` option to README

.editorconfig
Cleaned up editor configuration file.
=> Removed redundant editorconfig rules.

node-tests/.eslintrc.js, node-tests/acceptance/broccoli-test.js, node-tests/unit/project-localization-framework-test.js, package.json, yarn.lock
=> Replace plain "assert" with "chai" for better failure messages

.npmignore, .template-lintrc.js, blueprints/.jshintrc, blueprints/ember-cli-template-lint/recommended-files/.template-lintrc.js, blueprints/ember-cli-template-lint/recommended-with-bare-strings-files/.template-lintrc.js, broccoli-template-linter.js, config/ember-try.js, config/environment.js, config/release.js, ember-cli-build.js, index.js, tests/dummy/config/environment.js
=> Remove/Replace remaining JSHint directives

.eslintrc.js, blueprints/ember-cli-template-lint/index.js, broccoli-template-linter.js, ember-cli-build.js, index.js, lib/commands/print-failing.js, lib/plugins/remove-configuration-html-comments.js, lib/utils/project-localization-framework.js, node-tests/acceptance/broccoli-test.js, node-tests/blueprints/ember-cli-template-lint-test.js, node-tests/unit/eslint-test.js, node-tests/unit/project-localization-framework-test.js, package.json
... and update minimum Node version to 4
/cc @rwjblue
=> Use ES6 features

node-tests/acceptance/broccoli-test.js, package.json, yarn.lock
=> Replace "broccoli-test-helpers" with "broccoli-test-helper"

package.json, yarn.lock
=> Update ember-template-lint to 0.7.2

package.json
Incorporates fix for "empty errors" https://github.com/rwjblue/ember-template-lint/pull/250
=> Bump ember-template-lint.

index.js
=> Fix "this.ui.warn is not a function" error

README.md, broccoli-template-linter.js, node-tests/acceptance/broccoli-test.js, node-tests/blueprints/ember-cli-template-lint-test.js, package.json, yarn.lock
=> Reflect change in rule name from bare-strings to no-bare-strings
